// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/sms/async/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/sms/async/service.go -destination=internal/service/mocks/sms_service.mock.go -package=svcmock
//
// Package svcmock is a generated GoMock package.
package svcmock
