// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"github.com/jasonzhao47/cuddle/internal/repository"
	"github.com/jasonzhao47/cuddle/internal/repository/dao"
	"github.com/jasonzhao47/cuddle/internal/service"
	"github.com/jasonzhao47/cuddle/internal/web"
)

// Injectors from wire.go:

func InitArticleHandler(dao2 dao.ArticleDAO) *web.ArticleHandler {
	articleRepository := repository.NewArticleRepository(dao2)
	articleService := service.NewArticleService(articleRepository)
	logger := InitLog()
	articleHandler := web.NewArticleHandler(articleService, logger)
	return articleHandler
}

// wire.go:

var (
	thirdPartyDep          = wire.NewSet(InitDB, InitLog)
	articleServiceProvider = wire.NewSet(dao.NewArticleGormDAO)
)
