server:
  http:
    addr: :8089
    timeout: 1s
data:
  database:
    driver: mysql
    DSN: root:root@tcp(127.0.0.1:13306)/cuddle
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

kafka:
  addr: 127.0.0.1:9094
